package com.yemenptc.bss.coreservice.common.event;

enum CustomerEventType {
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_SUSPENDED, CUSTOMER_TERMINATED, CUSTOMER_RESUMED, KYC_VERIFIED
}

enum OrderEventType {
    ORDER_CREATED, ORDER_PROCESSING, ORDER_COMPLETED, ORDER_CANCELLED, ORDER_FAILED
}

enum BillingEventType {
    BALANCE_ADJUSTED, RECHARGE_COMPLETED, INVOICE_GENERATED, PAYMENT_COMPLETED, PAYMENT_FAILED
}

enum CatalogEventType {
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_RETIRED
}

enum ProvisioningEventType {
    SERVICE_ACTIVATED, SERVICE_DEACTIVATED, SERVICE_SUSPENDED, SERVICE_RESUMED, SERVICE_MODIFIED
}

enum RatingEventType {
    EVENT_RATED, BATCH_RATED
}
